version: '3.1'  # Secrets are only available since this version of Docker Compose
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8899:80
      
  orthanc:
    image: jodogne/orthanc-python:1.12.1
    ports:
      - 4242:4242
      - 8042:8042
    volumes:
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./config/dicomweb.json:/etc/orthanc/dicomweb.json:ro
      - ./python_plugin/handle_store.py:/etc/orthanc/python_plugin.py:ro
      - ./orthanc_data:/var/lib/orthanc/db
      - ./parse_data:/var/lib/orthanc/parse_data
    environment:
      - ORTHANC_NAME=HelloWorld